"""Shared audio chunking constants."""

from __future__ import annotations

# Qwen3-ForcedAligner-0.6B supports <= 5 min. Use 4 min as the default
# chunk size to leave a safety margin. ASR and alignment must use the same
# value so transcribe chunk metadata matches the chunks generated by /align.
TRANSCRIPTION_CHUNK_SECONDS = 240.0
