"""Shared inference concurrency limits for ML routes."""

from __future__ import annotations

import asyncio

ASR_MAX_CONCURRENT_INFERENCES = 1
TTS_MAX_CONCURRENT_INFERENCES = 1
QUALITY_MAX_CONCURRENT_INFERENCES = 1

ASR_INFERENCE_SEMAPHORE = asyncio.Semaphore(ASR_MAX_CONCURRENT_INFERENCES)
TTS_INFERENCE_SEMAPHORE = asyncio.Semaphore(TTS_MAX_CONCURRENT_INFERENCES)
QUALITY_INFERENCE_SEMAPHORE = asyncio.Semaphore(QUALITY_MAX_CONCURRENT_INFERENCES)
